# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Benjamin D. Hayum
email: bhayum@wisc.edu
description: >- # this means to ignore newlines until "baseurl:"
    Benjamin D. Hayum is a PhD student in Computer Science at the University of Wisconsin - Madison, 
    specializing in Sociotechnical AI Safety, Foundation Models, Learning Dynamics and Interpretability, 
    Evaluation and Robustness, and Neuroscience Parallels. He is the Founder and Research Lead of the
    Wisconsin AI Safety Initiative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benjaminhayum.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Personal Information:
author:
  name: "Benjamin D. Hayum"
  avatar: "/assets/images/ben-headshot.jpg"
  bio: "PhD Student in Computer Science at University of Wisconsin - Madison"
  location: "Madison, WI"
  email: "bhayum@wisc.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:bhayum@wisc.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BenjaminHayum"

# Sub-page links
navbar-links:
  Home: "/"
  Publications: "/publications"
  CV: "/cv"
  Teaching: "/teaching"
  Blog: "/blog"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

includes:
  - custom.css

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
